### ISSUE TITLE
cursor jsontocursor

### ISSUE THREAD

**Issue by benrojas01** [vespina/json#10]
Estimado Vcitor

por favor podrias indicarme cual es el error al tratar generar este cursor

de antemano muchas gracias

do json

oResp = JSON.httpRequest("GET",'https://api.agify.io/?name=michael')

?oResp
?oResp.JSON.name

JSON.toCursor(oResp.json, "QFILES",SET("DATASESSION"))

SELECT qfiles
brow

** me da un error que no logro corregir

**Comment by vespina** [comment]
Hola.  Hay un par de cosas involucradas aqui:

a) Cada vez que invocas a un metodo de JSON debes validar si ocurrio algun error.  Por ejemplo, despues de llamar a httpRequest:

```
IF JSON.lastError.hasError
   ?JSON.lastError.MEssage
   RETURN
ENDIF
```

b) El metodo toCursor requiere que el JSON a convertir sea un array de objetos con similares caracteristicas.  En tu caso, el endpoint que estas invocando devuelve un objeto, no un array:

```
{
	"count": 298219,
	"name": "michael",
	"age": 62
}
```

para que el metodo ToCursor funcione, deberias tener esto:

```
[
  {
	  "count": 298219,
	  "name": "michael",
	  "age": 62
  }
]
```

Entonces, aplicando estas consideraciones tu codigo quedaria asi:

```
do json

oResp = JSON.httpGet("https://api.agify.io/?name=michael")
IF JSON.lastError.hasError
   ?JSON.lastError.MEssage
   RETURN
ENDIF

JSON.toCursor("[" + oResp.Raw + "]", "QFILES",SET("DATASESSION"))
IF JSON.lastError.hasError
   ?JSON.lastError.MEssage
   RETURN
ENDIF

SELECT qfiles
BROWSE

```


Saludos

Victor Espina

**Comment by vespina** [comment]
Acabo de subir una nueva version que permite que tu codigo original funcione, convirtiendo el objeto simple en un array automaticamente.
