### ISSUE TITLE
analizar cadena desde cursor

### ISSUE THREAD

**Issue by benrojas01** [vespina/json#11]
Estimado Victor,

tengo el siguiente inconveniente;

necesito crear un cursor  desde fox para luego convertirlo en  json

cuando tengo el cursor llamado pasarApi hago lo siguiente:

DO JSON

LOCAL cjson, oRespn 
cjson = json.Stringify('pasarApi')
?cjson

omResp = json.parse(cjson) && aquí quiero  analizar las propiedades del json
IF JSON.lastError.hasError
   ?JSON.lastError.MEssage
   RETURN
ENDIF
?omResp

xx = omResp.rows.apl1
?xx

***** cuando quiero analizar la propiedad del objeto llamada apl1, me da el error   " Prperty apl1 is not found"

sin embargo en otras ocasiones he traído datos de internet y he podido leer esas propiedades sin problema alguno, no se que estoy haciendo mal o si al ser un json creado desde un cursor deba hacer un proceso distinto.

de hecho si quiero generar nuevamente el cursor lo puedo hacer sin problemas

JSON.toCursor(omResp.rows, "QFILES",SET("DATASESSION"))
SELECT qfiles
BROWSE

pero de ninguna manera puedo imprimir las propiedades del json

agradezco mucho tu valiosa ayuda

![error json](https://github.com/vespina/json/assets/32991065/c6cb15af-d8bc-4642-b0a2-53ce8a00ffb4)

**Comment by vespina** [comment]
La propiedad Rows es una coleccion, de modo que si haces:
`?omResp.Rows.Count`

te dara la cantidad de items en la coleccion.  Ahora, para acceder a un elemento particular de la coleccion, debes indicar el subindice:
`?omResp.Rows(1).apl1`

o si estas en una version anterior a VFP9:
`?omResp.Rows.Item(1).apl1`

Saludos

Victor Espina
