### ISSUE TITLE
About Beautify returning null

### ISSUE THREAD

**Issue by jhernancanom** [vespina/json#6]
When useFastParser = .T.
then Beautify returns null.

I tried the samples in ReadMe.

**Comment by vespina** [comment]
Check the latest version. First version that implemented fast parsing returned the original JS object, which can not be processed by Beautify method.  Latest versions applied a normalization process so now the result obtained with normal parsing or fast parsing is exactly the same and can be beautified.

Check this test using last version;

DO JSON

?JSON.Beautify('{ "firstName" : "Victor", "lastName": "Espina", "YOB": 1970 }')

JSON.useFastParser = .T.

?JSON.Beautify('{ "firstName" : "Victor", "lastName": "Espina", "YOB": 1970 }')

JSON.NormalizeResults = .F.

?JSON.Beautify('{ "firstName" : "Victor", "lastName": "Espina", "YOB": 1970 }')

**Comment by jhernancanom** [comment]
Chévere, colega.
Muchísimas gracias.

**Comment by jhernancanom** [comment]
Hola, Víctor.
Ejecuto en VFP9 y obtengo lo que hay en la primera imagen. **OK**.
Ejecuto en VFPA-x64 y obtengo lo que hay en la segunda imagen. 

[Test.prg.txt](https://github.com/vespina/json/files/10181840/Test.prg.txt)

![image](https://user-images.githubusercontent.com/5818845/206350886-bfdcec9f-1c93-4feb-bf48-bd644583839a.png)

![image](https://user-images.githubusercontent.com/5818845/206350751-31afb3c0-0845-4ed4-bd8d-991bcf327eb6.png)

**Comment by vespina** [comment]
Hola Hernan.  No habia visto este post.  En el caso del fastparsing quizas el problema viene por el uso del componente VBScript desde un ambiente 64bits.  Sin embargo, eso no explica porque no funciona el beautify con el parsing normal.  Lamentablemente no trabajo con VFPA (aun) asi que no te sabria decir porque no funciona, pero lo tendre en cuenta para revisarlo en cuanto tenga oportunidad.
