### ISSUE TITLE
BUG: VFP_JSON_BEAUTIFY_MARGIN

### ISSUE THREAD

**Issue by rcanop** [vespina/json#7]
Hola Victor, me parece que ese define de json.prg debería estar en fuera del `#IF VFP_JSON_LANG=="EN"` ya que si ese define se establece en `"ES"`, no se cargará.

Un saludo Rafael Cano.

**Comment by vespina** [comment]
Tienes toda la razon. Gracias por el tip, amigo.  Corregido.
