### ISSUE TITLE
HEADERS

### ISSUE THREAD

**Issue by benrojas01** [vespina/json#8]
Buenas noches estimado Victor

quisiera saber si es posible  a través de tu libreria autenticar con un token o coockie,  ya que estoy construyendo un api para consulta de datos 

muchas gracias por tu respuesta y orientación

saludos,

**Comment by vespina** [comment]
En teoria si.  Yo he utilizado autenticacion por API Key usando un header "Authorization: Bearer xxxxxxx", pero teoricamente deberia ser posible trabajar con cualquier mecanismo de autorizacion basado en Headers o incluso cookies.
